## Numpy

NumPy is an extension to the Python programming language, adding support for large, multidimensional
(numerical) arrays and matrices, along with a large library of high-level mathematical
functions to operate on these arrays.


In [2]:
import numpy as np

## Create arrays:

In [2]:
arr = np.array([2,3,4]) #1d array
arr

array([2, 3, 4])

In [3]:
arr1 = np.array([range(1,5),range(5,9)])  #2d array
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
arr2 = np.array([[1,2],[3,4]], dtype = complex)
arr2

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

## Converting array to list

In [5]:
print(arr1.tolist())
print(arr1)

[[1, 2, 3, 4], [5, 6, 7, 8]]
[[1 2 3 4]
 [5 6 7 8]]


## Creating special arrays:

## 1.zero matrix

In [6]:
spl = np.zeros(10)  #function zero create zero values
print(spl)
spl1 = np.zeros((3,6)) #zero matrix
spl1

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

## 2.Ones matrix

In [7]:
spl2 = np.ones(10) #function ones create one values
print(spl2)
spl3 = np.ones((3,4))
spl3
spl4=np.ones((2,3,4), dtype=np.int16)
spl4

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

## 3.Random matrix

In [8]:
np.empty((2,3), dtype=np.int32)  # can also regular int

array([[0, 0, 0],
       [0, 0, 0]])

In [9]:
np.logspace(0,3,4)  #10^0 to 10^3 with 4 values

array([   1.,   10.,  100., 1000.])

## range is arange in numpy

In [10]:
np.arange(10, 30, 5) #works like range. 5 is interval here

array([10, 15, 20, 25])

In [11]:
np.arange(10.3, 20.2, 2.5)

array([10.3, 12.8, 15.3, 17.8])

## linspace

In [12]:
np.linspace(0, 3, 9) # fetch 9 number between 0 and 3. It includes 3

array([0.   , 0.375, 0.75 , 1.125, 1.5  , 1.875, 2.25 , 2.625, 3.   ])

In [13]:
from numpy import pi
x = np.linspace(0,2*pi,10)
x

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

In [14]:
np.sin(x)

array([ 0.00000000e+00,  6.42787610e-01,  9.84807753e-01,  8.66025404e-01,
        3.42020143e-01, -3.42020143e-01, -8.66025404e-01, -9.84807753e-01,
       -6.42787610e-01, -2.44929360e-16])

## Random

## rand

In [15]:
np.random.rand(3,2) # gives random number from [0,1)

array([[0.99207693, 0.5435105 ],
       [0.96588491, 0.36032706],
       [0.15422016, 0.31383894]])

## randint

In [16]:
np.random.randint(0,10, size=10)  # gets 10 random number in range [0,10)

array([9, 3, 7, 9, 5, 0, 4, 8, 0, 9])

In [17]:
np.random.randint(10, size=10) # if nothing is given, it will take it as highest number and low as 0

array([7, 9, 4, 3, 3, 9, 5, 7, 1, 0])

In [18]:
np.random.randint(10, size=(2, 4))  #creates 2*4 array

array([[8, 5, 6, 8],
       [4, 1, 9, 3]])

In [19]:
np.random.randint(1, [3, 5, 10]) #Generate a 1 by 3 array with 3 different lower bounds. 1st value <3, 2nd value<5 ...

array([2, 4, 4])

## randn

In [20]:
np.random.randn() #fetch values from std normal distribution

-0.8859952643280948

For random samples from N(mu,sigma) use:

sigma * np.random.randn(...) + mu

In [21]:
3 + 2.2 * np.random.randn(2,4)  #for N(3,2.2) in 2,4 array

array([[0.34969364, 1.99299885, 2.49220157, 3.30341092],
       [5.37354113, 5.15623879, 3.18104231, 2.57280003]])

## Reshape

In [22]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [24]:

np.arange(100).reshape(10,10)  #reshape by rows

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [26]:
np.arange(100).reshape(10, 10, order='F') #reshape by columns

array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
       [ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92],
       [ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93],
       [ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
       [ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
       [ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96],
       [ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97],
       [ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98],
       [ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99]])

## Three numbers in reshape

In [51]:
rr = np.arange(24)
#rr.reshape(3,4) will give error because it has 24 elements
rr1 = rr.reshape(3,4,2) # # 3 means it will have 3 parent list that has a structure of (4, 2)
rr1

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [52]:
rr1.ndim # reshape with 3 values has three dim

3

## Dim

In [5]:
ww = np.arange(16)
ww  #Note that there is single bracket.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [6]:
ww.shape

(16,)

In [9]:
ww1 = ww.reshape(1, -1)
ww1  #Note that there is double bracket.

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [10]:
ww1.shape

(1, 16)

In [53]:
ww2 = ww.reshape(4,4)
ww2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
ww2.shape

(4, 4)

In [55]:
ww2.ndim  #reshape with 2 values has 2 dimension

2

## Reshaping

In [67]:
k = np.arange(20).reshape(5,4)
k

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [68]:
k.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [69]:
k.reshape((4,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [70]:
k.reshape(5,-1) #having -1 will reshapes the another dimension automatically

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

## Transpose

In [71]:
p_new.T

array([[0, 1]])

## flatten

In [72]:
arr32 = b.flatten() #converts to single row
arr32

array([0, 1, 2, 3])

In [73]:
arr33 = b.ravel() #same as flatten
arr33

array([0, 1, 2, 3])

## Floor

In [74]:
l = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0]) # Greatest integer
np.floor(l)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

## Basic Operations

In [25]:
a = np.array([20,30,40,50])
b = np.arange(4)
c = a - b
c

array([20, 29, 38, 47])

In [26]:
b**2 

array([0, 1, 4, 9], dtype=int32)

In [27]:
c<10

array([False, False, False, False])

## Multiplication

1. Element wise product

In [28]:
s = np.array([[1,3],
             [2,4]])
d = np.array([[10,20],
             [20,30]])
s * d

array([[ 10,  60],
       [ 40, 120]])

2. Matrix multiplication

In [29]:
s @ d

array([[ 70, 110],
       [100, 160]])

In [30]:
s .dot(d) #another way of matrix multiplication

array([[ 70, 110],
       [100, 160]])

## array is memoryless

In [31]:
q = np.ones((2,3), dtype=int)
w = np.random.random((2,3)) # returns value from interval [0,1)
q*=3
q

array([[3, 3, 3],
       [3, 3, 3]])

In [32]:
w += q
w

array([[3.0943084 , 3.85052541, 3.27454802],
       [3.39396971, 3.63909339, 3.40386463]])

In [33]:
e = np.arange(24).reshape(4,6)
e

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

## basic functions

In [34]:
e.sum() #total sum

276

In [35]:
e.min()

0

In [36]:
e.argmin() #gives index position. In this example index and values are same

0

In [37]:
e.max()

23

In [38]:
e.argmax() #gives index position. In this example index and values are same

23

In [39]:
e.sum(axis=0) #add columns

array([36, 40, 44, 48, 52, 56])

In [40]:
e.sum(axis=1) #add rows

array([ 15,  51,  87, 123])

In [41]:
e.min(axis=0) #mini of each columns

array([0, 1, 2, 3, 4, 5])

In [42]:
e.cumsum(axis=1) # cummulative sum along each row

array([[  0,   1,   3,   6,  10,  15],
       [  6,  13,  21,  30,  40,  51],
       [ 12,  25,  39,  54,  70,  87],
       [ 18,  37,  57,  78, 100, 123]], dtype=int32)

In [43]:
np.exp(e)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
        8.88611052e+06, 2.41549528e+07],
       [6.56599691e+07, 1.78482301e+08, 4.85165195e+08, 1.31881573e+09,
        3.58491285e+09, 9.74480345e+09]])

In [44]:
np.sqrt(e)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
        3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ,
        4.12310563],
       [4.24264069, 4.35889894, 4.47213595, 4.58257569, 4.69041576,
        4.79583152]])

## Indexing, slicing and iterating

In [45]:
r = np.arange(10)**2
r

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [46]:
r[4]

16

In [47]:
r[2:4]

array([4, 9], dtype=int32)

In [48]:
r[0:6:2]

array([ 0,  4, 16], dtype=int32)

In [49]:
r[0:6:2] = 100
r

array([100,   1, 100,   9, 100,  25,  36,  49,  64,  81], dtype=int32)

In [50]:
for i in r:
    print(i**0.5)

10.0
1.0
10.0
3.0
10.0
5.0
6.0
7.0
8.0
9.0


## Fetching specific rows

In [51]:
t = np.arange(20).reshape(5,4)
t

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [52]:
t[1] #print rows

array([4, 5, 6, 7])

In [53]:
t[2,3] # third row forurth column

11

In [54]:
t[:,1 ] #print column 2

array([ 1,  5,  9, 13, 17])

In [55]:
t[0:4, 1] #print 4 values from 2nd column

array([ 1,  5,  9, 13])

In [56]:
t[1,: ] #print row 2

array([4, 5, 6, 7])

In [57]:
t[1, 0:3 ] #print 2 values in every row

array([4, 5, 6])

In [58]:
t[1:3, 0:2] # print 2 numbers in row 2 and 3 and print 2 numbers in column 0 and 1

array([[4, 5],
       [8, 9]])

## 3d array(two stacked 2d arrays)

In [59]:
y = np.array([[[0, 1, 2],
              [10, 11, 12]],
             [[100, 101, 102],
             [110, 112, 113]]])
y

array([[[  0,   1,   2],
        [ 10,  11,  12]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [60]:
y.shape

(2, 2, 3)

In [61]:
y[1,:,:]

array([[100, 101, 102],
       [110, 112, 113]])

Iterating over multidimensional arrays

In [62]:
for i in y:  #prints rows
    print(i)
    

[[ 0  1  2]
 [10 11 12]]
[[100 101 102]
 [110 112 113]]


In [63]:
for element in y.flat:  #flat fetches all the values
    print(element)

0
1
2
10
11
12
100
101
102
110
112
113


## Adding a new axis

In [56]:
p= np.arange(3)
p

array([0, 1, 2])

In [57]:
p_new = p[:,np.newaxis] #add one dimension
p_new

array([[0],
       [1],
       [2]])

In [59]:
p_new = p[:,None,None] # newaxis is none. # two values adds two dimension
p_new

3

## stacking

In [23]:
ee = np.arange(1,13)
ff = np.arange(13,25)
np.stack((ee,ff)) # horizontal stacking

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [24]:
np.stack((ee,ff),axis=1) #vertical stacking

array([[ 1, 13],
       [ 2, 14],
       [ 3, 15],
       [ 4, 16],
       [ 5, 17],
       [ 6, 18],
       [ 7, 19],
       [ 8, 20],
       [ 9, 21],
       [10, 22],
       [11, 23],
       [12, 24]])

In [19]:
j = np.floor(10*np.random.random((2,2)))
j

array([[5., 4.],
       [5., 4.]])

In [20]:
h = np.floor(10*np.random.random((2,2)))
h

array([[0., 4.],
       [7., 6.]])

In [22]:
np.stack((j,h)) #horizontal stacking

array([[[5., 4.],
        [5., 4.]],

       [[0., 4.],
        [7., 6.]]])

In [25]:
np.stack((j,h),axis=1) #vertical stacking

array([[[5., 4.],
        [0., 4.]],

       [[5., 4.],
        [7., 6.]]])

## concatenate

In [108]:
np.concatenate((j,h),axis=0) #Join a sequence of arrays along an existing axis

array([[9., 5.],
       [9., 8.],
       [8., 5.],
       [5., 1.]])

In [109]:
np.concatenate((j,h),axis=1)

array([[9., 5., 8., 5.],
       [9., 8., 5., 1.]])

## vstack

In [77]:
np.vstack((j,h)) #stack in the vertical axis

array([[9., 5.],
       [9., 8.],
       [8., 5.],
       [5., 1.]])

## hstack

In [78]:
np.hstack((j,h)) #stack in the horizontal axis

array([[9., 5., 8., 5.],
       [9., 8., 5., 1.]])

## column stack vs hstack

In [79]:
m = np.array([4,2])
m

array([4, 2])

In [80]:
n = np.array([3,1])
n

array([3, 1])

In [81]:
np.column_stack((m,n))  #creates 2d array

array([[4, 3],
       [2, 1]])

In [82]:
np.hstack((m,n))

array([4, 2, 3, 1])

## splitting

In [83]:
b = np.arange(16)
b


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## hsplit

In [84]:
np.hsplit(b,4)  #split b into 3

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14, 15])]

In [85]:
np.hsplit(b,(3,4)) # Split a after the third and the fourth column

[array([0, 1, 2]),
 array([3]),
 array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])]

In [86]:
b = b.reshape(4,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## vsplit

In [87]:
np.vsplit(b, 4)  #splits vertically

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [88]:
np.vsplit(b, (2,3)) 

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

## array_split

In [89]:
np.array_split(b, 3)  #array split

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

## Copy

In [90]:
v = np.arange(12)
c = v.copy().reshape(3,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## seed

In [91]:
np.random.seed(0)        # running seed everytime before random number gives the same random value
perm = np.random.permutation(10)
print (perm)
np.random.seed(1)        #specific seed gives specific value
perm = np.random.permutation(10)
print(perm)
np.random.seed(0) 
perm = np.random.permutation(10)
print (perm)
perm = np.random.permutation(10) 
print(perm)
np.random.seed(1) 
perm = np.random.permutation(10)
print(perm)

[2 8 4 9 1 6 7 3 0 5]
[2 9 6 4 0 3 1 7 8 5]
[2 8 4 9 1 6 7 3 0 5]
[3 5 1 2 9 8 0 6 7 4]
[2 9 6 4 0 3 1 7 8 5]


## sort

In [92]:
x = np.random.rand(2,3)
x

array([[0.38791074, 0.66974604, 0.93553907],
       [0.84631092, 0.31327352, 0.52454816]])

In [93]:
np.sort(x,axis=0)

array([[0.38791074, 0.31327352, 0.52454816],
       [0.84631092, 0.66974604, 0.93553907]])

In [94]:
np.argsort(x,axis=1) #shows the index value to be changed

array([[0, 1, 2],
       [1, 2, 0]], dtype=int64)

## mgrid

In [95]:
np.mgrid[0:5,0:5] #creates multidimensional coordinate matrices from coordinate vectors.

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

## Conversions

## Astype

In [96]:
qq = np.array([1,3,5.5]) 
qq.astype(int)  # converts into specific type


array([1, 3, 5])

## atleast_1d

In [99]:
np.atleast_1d(1.0) #Convert inputs to arrays with at least one dimension

array([1.])

In [102]:
np.atleast_1d(1, [3, 4])

[array([1]), array([3, 4])]

## atleast_2d

In [103]:
np.atleast_2d(3.0) #views in atleast 2d

array([[3.]])

In [104]:
np.atleast_2d(1, [1, 2], [[1, 2]])

[array([[1]]), array([[1, 2]]), array([[1, 2]])]